"""Add comment_triggers and leads tables

Revision ID: 91b370949324
Revises: 001
Create Date: 2026-05-13 15:18:45.824552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b370949324'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('post_media_id', sa.String(length=64), nullable=False),
    sa.Column('comment_id', sa.String(length=64), nullable=False),
    sa.Column('commenter_username', sa.String(length=64), nullable=True),
    sa.Column('comment_text', sa.String(length=500), nullable=True),
    sa.Column('reply_text', sa.String(length=500), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id')
    )
    op.create_table('comment_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('post_instagram_media_id', sa.String(length=100), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('initial_message', sa.Text(), nullable=False),
    sa.Column('follow_up_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('commenter_ig_user_id', sa.String(length=100), nullable=False),
    sa.Column('commenter_username', sa.String(length=100), nullable=False),
    sa.Column('post_instagram_media_id', sa.String(length=100), nullable=False),
    sa.Column('comment_id', sa.String(length=100), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('dm_sent', sa.Boolean(), nullable=False),
    sa.Column('dm_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'REPLIED', 'QUALIFIED', 'CLOSED', name='leadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['comment_triggers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', name='uq_leads_comment_id')
    )
    op.add_column('contents', sa.Column('audio_name', sa.String(length=255), nullable=True))
    op.add_column('contents', sa.Column('is_ai_generated_content', sa.Boolean(), nullable=False))
    op.add_column('contents', sa.Column('cover_url', sa.Text(), nullable=True))
    op.add_column('contents', sa.Column('comment_trigger_keyword', sa.String(length=100), nullable=True))
    op.add_column('contents', sa.Column('comment_trigger_dm_message', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_contents_account_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_status'), table_name='contents')
    op.drop_index(op.f('ix_engagement_metrics_account_id'), table_name='engagement_metrics')
    op.drop_index(op.f('ix_engagement_metrics_media_id'), table_name='engagement_metrics')
    op.drop_index(op.f('ix_engagement_metrics_recorded_at'), table_name='engagement_metrics')
    op.add_column('scheduled_posts', sa.Column('first_comment_text', sa.Text(), nullable=True))
    op.add_column('scheduled_posts', sa.Column('first_comment_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scheduled_posts', sa.Column('first_comment_posted', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_scheduled_posts_account_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_scheduled_time'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_status'), table_name='scheduled_posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scheduled_posts_status'), 'scheduled_posts', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_scheduled_time'), 'scheduled_posts', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_account_id'), 'scheduled_posts', ['account_id'], unique=False)
    op.drop_column('scheduled_posts', 'first_comment_posted')
    op.drop_column('scheduled_posts', 'first_comment_due_at')
    op.drop_column('scheduled_posts', 'first_comment_text')
    op.create_index(op.f('ix_engagement_metrics_recorded_at'), 'engagement_metrics', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_engagement_metrics_media_id'), 'engagement_metrics', ['instagram_media_id'], unique=False)
    op.create_index(op.f('ix_engagement_metrics_account_id'), 'engagement_metrics', ['account_id'], unique=False)
    op.create_index(op.f('ix_contents_status'), 'contents', ['status'], unique=False)
    op.create_index(op.f('ix_contents_account_id'), 'contents', ['account_id'], unique=False)
    op.drop_column('contents', 'comment_trigger_dm_message')
    op.drop_column('contents', 'comment_trigger_keyword')
    op.drop_column('contents', 'cover_url')
    op.drop_column('contents', 'is_ai_generated_content')
    op.drop_column('contents', 'audio_name')
    op.drop_table('leads')
    op.drop_table('comment_triggers')
    op.drop_table('comment_replies')
    # ### end Alembic commands ###
